branch-defaults:
    master:
        environment: Marketplace64Backend-env
global:
    application_name: marketplace-64-backend
    default_ec2_keyname: e-ffrm9mnt5k
    default_platform: Node.js running on 64bit Amazon Linux/4.14.1
    default_region: us-east-2
    sc: git
